<?php
$config = \simulation\Config::get('site');
?>
<!DOCTYPE HTML>
<html>
	<head>
		<title><?=$config['title'];?></title>
		<link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
		<script type="text/javascript" src="/js/jquery-2.1.3.min.js"></script>
		<script type="text/javascript" src="/js/bootstrap.min.js"></script>
	</head>
	<body>
		<nav class="navbar navbar-default" role="navigation">
			<div class="container-fluid">
				<div class="navbar-header">
					<a class="navbar-brand" href="/">Simulation</a>
				</div>
				<form class="navbar-form navbar-right" role="search">
					<a href="/server/add" class="btn btn-default">
						<span class="glyphicon glyphicon-plus-sign"></span>
							Add Server
					</a>
				</form>
			</div>
		</nav>
		<div class="container">
			<!-- Specific Page Content Goes Here -->
			<?php $this->content(); ?>
		</div>
		<script type="text/javascript">
			$('[data-toggle="popover"]').popover();
		</script>
	</body>
</html>
